name: Docker CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        if [ -f Dockerfile ]; then
          docker build -t lab09-app:latest .
        else
          echo "Dockerfile не найден, автоматическая сборка базового контейнера"
          echo "FROM ubuntu:latest" > Dockerfile
          docker build -t lab09-app:latest .
        fi
